BYZANTIUM_FORK_BLOCK: 4370000
CONSTANTINOPLE_FORK_BLOCK: 7280000

# Altair
INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 50331648
MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR: 64
PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR: 2

# Sync protocol
MIN_SYNC_COMMITTEE_PARTICIPANTS: 1
UPDATE_TIMEOUT: 8192

# Bellatrix
INACTIVITY_PENALTY_QUOTIENT_BELLATRIX: 16777216
MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX: 32
PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX: 3

# Execution
MAX_BYTES_PER_TRANSACTION: 1073741824
MAX_TRANSACTIONS_PER_PAYLOAD: 1048576
BYTES_PER_LOGS_BLOOM: 256
MAX_EXTRA_DATA_BYTES: 32

# Time parameters
RANDAO_PENALTY_EPOCHS: 2
EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS: 32768
EPOCHS_PER_CUSTODY_PERIOD: 16384
CUSTODY_PERIOD_TO_RANDAO_PADDING: 2048
MAX_CHUNK_CHALLENGE_DELAY: 32768

# Max operations
MAX_CUSTODY_KEY_REVEALS: 256
MAX_EARLY_DERIVED_SECRET_REVEALS: 1
MAX_CUSTODY_CHUNK_CHALLENGES: 4
MAX_CUSTODY_CHUNK_CHALLENGE_RESP: 16
MAX_CUSTODY_SLASHINGS: 1

# Reward and penalty quotients
EARLY_DERIVED_SECRET_REVEAL_SLOT_REWARD_MULTIPLE: 2
MINOR_REWARD_QUOTIENT: 256

# Misc
MAX_COMMITTEES_PER_SLOT: 64
TARGET_COMMITTEE_SIZE: 128
MAX_VALIDATORS_PER_COMMITTEE: 2048
SHUFFLE_ROUND_COUNT: 90
HYSTERESIS_QUOTIENT: 4
HYSTERESIS_DOWNWARD_MULTIPLIER: 1
HYSTERESIS_UPWARD_MULTIPLIER: 5

# Fork Choice
SAFE_SLOTS_TO_UPDATE_JUSTIFIED: 8

# Gwei values
MIN_DEPOSIT_AMOUNT: 1000000000
MAX_EFFECTIVE_BALANCE: 32000000000
EFFECTIVE_BALANCE_INCREMENT: 1000000000

# State list lengths
EPOCHS_PER_HISTORICAL_VECTOR: 65536
EPOCHS_PER_SLASHINGS_VECTOR: 8192
HISTORICAL_ROOTS_LIMIT: 16777216
VALIDATOR_REGISTRY_LIMIT: 1099511627776

# Reward and penalty quotients
BASE_REWARD_FACTOR: 64
WHISTLEBLOWER_REWARD_QUOTIENT: 512
PROPOSER_REWARD_QUOTIENT: 8
INACTIVITY_PENALTY_QUOTIENT: 67108864
MIN_SLASHING_PENALTY_QUOTIENT: 128
PROPORTIONAL_SLASHING_MULTIPLIER: 1

# Max operations per block
MAX_PROPOSER_SLASHINGS: 16
MAX_ATTESTER_SLASHINGS: 2
MAX_ATTESTATIONS: 128
MAX_DEPOSITS: 16
MAX_VOLUNTARY_EXITS: 16

# Misc
MAX_SHARDS: 1024
INITIAL_ACTIVE_SHARDS: 64
SAMPLE_PRICE_ADJUSTMENT_COEFFICIENT: 8
MAX_SHARD_PROPOSER_SLASHINGS: 16
MAX_SHARD_HEADERS_PER_SHARD: 4
SHARD_STATE_MEMORY_SLOTS: 256
BLOB_BUILDER_REGISTRY_LIMIT: 1099511627776
MAX_SAMPLES_PER_BLOCK: 2048
TARGET_SAMPLES_PER_BLOCK: 1024

# Gwei values
MAX_SAMPLE_PRICE: 8589934592
MIN_SAMPLE_PRICE: 8

# Max operations per block
MAX_BLS_TO_EXECUTION_CHANGES: 16

# Withdrawals processing
MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP: 16384
